Assign Role API
PEC-CSS/acm-website-backend pull request #21
Opened 2023-07-10 16:11 UTC by notSanil

Description: Added API endpoint and changes for #12. Additionally, changed the designation column from string to Enum type in code.

2023-07-10 17:10 UTC, harshjohar requested changes
I am unsure about the `@Modifying` part, rest it looks good to me :)

2023-07-10 17:10 UTC, harshjohar commented on src/main/java/com/pecacm/backend/repository/UserRepository.java
> +    void updateRoleByEmail(String email, Role newRole);
Shouldn't there be `@Modifying` annotation present here to modify state of db.

2023-07-10 18:03 UTC, ken1000minus7 requested changes

2023-07-10 18:03 UTC, ken1000minus7 commented on src/main/java/com/pecacm/backend/services/UserService.java
> +        throw new AcmException(ErrorConstants.USER_UNAUTHORIZED);
Add response code 401

2023-07-11 09:26 UTC, ken1000minus7 approved these changes
Lgtm

2023-07-11 09:26 UTC, harshjohar approved these changes
lgtm

2023-07-11 09:27 UTC, merged