Made API end points
PEC-CSS/acm-website-backend pull request #25
Opened 2023-07-12 16:35 UTC by rawalabhinav

Created end points for GET, PUT, POST and DELETE REQUESTS

2023-07-12 16:49 UTC, ken1000minus7 requested changes

2023-07-12 16:49 UTC, ken1000minus7 commented on src/main/java/com/pecacm/backend/constants/UserRole.java
> +}
This is same as [Role.java](https://github.com/PEC-CSS/acm-website-backend/blob/main/src/main/java/com/pecacm/backend/enums/Role.java) so it's not required

2023-07-12 16:49 UTC, ken1000minus7 commented on src/main/java/com/pecacm/backend/constants/EventRole.java
> +}
move it to enums package

2023-07-12 16:49 UTC, ken1000minus7 commented on src/main/java/com/pecacm/backend/BackendApplication.java
> +import org.springframework.context.annotation.ComponentScan;
Remove this import if not being used

2023-07-12 16:49 UTC, ken1000minus7 commented on src/main/java/com/pecacm/backend/controllers/EventController.java
> +@RequestMapping("v1/events")
```suggestion
@RequestMapping("/v1/events")
```

2023-07-12 16:49 UTC, ken1000minus7 commented on src/main/java/com/pecacm/backend/entities/Event.java
> -
should this be removed ? @harshjohar

2023-07-12 16:49 UTC, ken1000minus7 commented on src/main/resources/application.yml
> +    password: acmheads
Do not push changes in `application.yml`

2023-07-12 16:49 UTC, ken1000minus7 commented on src/main/java/com/pecacm/backend/controllers/EventController.java
> +    }
Recheck the paths for these endpoints

2023-07-12 20:11 UTC, rawalabhinav commented on src/main/java/com/pecacm/backend/controllers/EventController.java
> +    }
ok

2023-07-13 18:45 UTC, harshjohar commented on src/main/java/com/pecacm/backend/entities/Event.java
> -
yeah, now we have attendance inside system

2023-07-22 17:07 UTC, ken1000minus7 commented on src/main/java/com/pecacm/backend/controllers/EventController.java
> +        }
No need of this

2023-07-22 17:09 UTC, ken1000minus7 commented on src/main/java/com/pecacm/backend/services/EventService.java
> +    }
return the created event itself instead of boolean

2023-07-22 17:10 UTC, ken1000minus7 commented on src/main/java/com/pecacm/backend/services/EventService.java
> +    }
Also add validations (or maybe we can add in future and assume for now that event data from frontend is valid, ur choice)

2023-07-22 17:11 UTC, ken1000minus7 commented on src/main/java/com/pecacm/backend/services/EventService.java
> +    }
check if user exists

2023-07-22 17:12 UTC, ken1000minus7 commented on src/main/java/com/pecacm/backend/controllers/EventController.java
> +                 .orElseThrow(() -> new ResourceNotFoundException("Event doesn't not exist with id :" + eventId));
handle the event not existing thing in service layer

2023-07-22 17:13 UTC, ken1000minus7 commented on src/main/java/com/pecacm/backend/services/EventService.java
> +    }
Any reason for getting the events from attendance table instead of events? 🤔

2023-07-22 17:14 UTC, ken1000minus7 commented on src/main/java/com/pecacm/backend/services/EventService.java
> +    }
https://github.com/PEC-CSS/acm-website-backend/pull/25/files#r1271321693

2023-07-22 17:43 UTC, rawalabhinav commented on src/main/java/com/pecacm/backend/services/EventService.java
> +    }
TODOed already 🖖🏼 Will complete by EOD

2023-07-22 17:43 UTC, rawalabhinav commented on src/main/java/com/pecacm/backend/controllers/EventController.java
> +                 .orElseThrow(() -> new ResourceNotFoundException("Event doesn't not exist with id :" + eventId));
Alright

2023-07-22 17:45 UTC, rawalabhinav commented on src/main/java/com/pecacm/backend/services/EventService.java
> +    }
Events table only consists of events created, attendance table contains participant attendance across all events. Check entities for the structure. Thought of separation of concerns while making the attendance table.

2023-07-22 17:47 UTC, rawalabhinav commented on src/main/java/com/pecacm/backend/services/EventService.java
> +    }
:salute: kept it empty for the clashing condition, will return event.

2023-08-06 21:14 UTC, closed without merging