Feat leaderboard
PEC-CSS/acm-website-backend pull request #55
Opened 2023-10-11 16:39 UTC by harasees-singh

added paged responses for apis /user/leaderboard and /user/leaderboard/{batch} where batch = 2023, 2024 etc.

2023-10-11 18:20 UTC, harshjohar requested changes

2023-10-11 18:20 UTC, harshjohar commented on src/main/java/com/pecacm/backend/controllers/UserController.java
> +        if (pageSize == null) pageSize = Integer.MAX_VALUE; // user count will never exceed a billion
When pageSize is null, return first 20, all users will crash the response json on front end

2023-10-11 18:20 UTC, harshjohar commented on src/main/java/com/pecacm/backend/controllers/UserController.java
> +        if (pageSize == null) pageSize = Integer.MAX_VALUE; // user count will never exceed a billion
Same here, return first 20

2023-10-12 04:55 UTC, harasees-singh commented
sample output for `http://localhost:8080/v1/user/leaderboard/2024?pageSize=2`

{
    "content": [
        {
            "id": 1,
            "name": "Harshpreet Singh Johar",
            "email": "harshpreetsinghjohar.btcse20@pec.edu.in",
            "password": "$2a$10$G6dacV8fB/XLNLT7Hiqhge.n6je3jotFrMpHv9Ng6rvQ5QM.mRHI.",
            "batch": 2024,
            "branch": "CSE",
            "dp": null,
            "sid": 20103076,
            "verified": true,
            "designation": "Admin",
            "xp": 0
        },
        {
            "id": 2,
            "name": "Harasees Singh",
            "email": "haraseessingh.btcse20@pec.edu.in",
            "password": "$2a$10$aRANvDzCmBJuOoLjUcOtd.qPCNqwKXUs0E1r3SU1nOfxEwopZkxd2",
            "batch": 2024,
            "branch": "CSE",
            "dp": null,
            "sid": 20103074,
            "verified": true,
            "designation": "Member",
            "xp": 0
        }
    ],
    "pageable": {
        "sort": {
            "empty": true,
            "sorted": false,
            "unsorted": true
        },
        "offset": 0,
        "pageNumber": 0,
        "pageSize": 2,
        "paged": true,
        "unpaged": false
    },
    "last": true,
    "totalPages": 1,
    "totalElements": 2,
    "first": true,
    "size": 2,
    "number": 0,
    "sort": {
        "empty": true,
        "sorted": false,
        "unsorted": true
    },
    "numberOfElements": 2,
    "empty": false
}

2023-10-12 05:33 UTC, harshjohar approved these changes

2023-10-12 05:33 UTC, merged