forget password feature
PEC-CSS/acm-website-backend pull request #88
Opened 2023-10-21 14:57 UTC by 13jksingh

Fixes https://github.com/PEC-CSS/acm-website-backend/issues/81

2023-10-21 17:42 UTC, harasees-singh commented on src/main/java/com/pecacm/backend/controllers/UserController.java
> +    }
aren't you sending back the verification token in response to a GET request with provided email ? this way anyone would be able to make a GET request with someone else's email and change their password.

2023-10-21 17:43 UTC, harasees-singh reviewed
requires changes

2023-10-21 17:47 UTC, harasees-singh commented on src/main/java/com/pecacm/backend/services/UserService.java
> +    }
encode the password before saving it to db

2023-10-21 20:17 UTC, ken1000minus7 requested changes

2023-10-21 20:17 UTC, ken1000minus7 commented on src/main/java/com/pecacm/backend/repository/ForgetPasswordTokenRepository.java
> +    ForgetPasswordToken findByToken(UUID token);
```suggestion
    Optional<ForgetPasswordToken> findByToken(UUID token);
```

2023-10-21 20:17 UTC, ken1000minus7 commented on src/main/java/com/pecacm/backend/services/ForgetPasswordService.java
> +    }
Throw 404 if token doesn't exist

2023-10-23 11:07 UTC, harasees-singh commented
issue solved, closing PR

2023-10-23 11:07 UTC, closed without merging