Feat forgot password
PEC-CSS/acm-website-backend pull request #89
Opened 2023-10-22 05:57 UTC by harasees-singh

* added GET v1/user/forgot-password which sends an email with UUID token to the provided username only if user is verified
* added POST v1/user/forgot-password which verifies the provided UUID token with the latest UUID token in `VerificationToken` repository and sends back `AuthenticationResponse` in case of success
* once the user updates the password the Verification Token corresponding to the User is updated as well so that the same UUID cannot be used multiple times to update the password

2023-10-22 08:13 UTC, ken1000minus7 commented
Isn't #88 for the same issue?

2023-10-22 08:20 UTC, harasees-singh commented
@ken1000minus7 yes it is, I had a better implementation in my mind so I went ahead with it

2023-10-22 17:48 UTC, harshjohar requested changes

2023-10-22 17:48 UTC, harshjohar commented on src/main/java/com/pecacm/backend/services/EmailService.java
> +        );
Draft a email here, because this will be the body of email, not some response code.

Use case is like this :
- user click forgot
- gets email
- clicks on link in mail => this link will be a frontend route which will open the forgot password page to fill new pass
- new pass page and change pass api

2023-10-22 18:30 UTC, harasees-singh commented on src/main/java/com/pecacm/backend/services/EmailService.java
> +        );
adding a placeholder email for now, please create a separate issue for this.

2023-10-23 10:50 UTC, harshjohar approved these changes
LGTM

2023-10-23 10:50 UTC, harshjohar commented
I hope the email has the link, not just the url in form of text @harasees-singh

2023-10-23 10:55 UTC, merged